### ISSUE TITLE
Submit to ego?

### ISSUE THREAD

**Issue by jibsaramnim** [laurinneff/gnome-shell-extension-zenbook-duo#3]
Do you think there would be [anything preventing you](https://gjs.guide/extensions/review-guidelines/review-guidelines.html#basics) from having the extension submitted to and published on the GNOME extensions site? It might make it even nicer for people if they can just enable it from the site, rather than having to build it themselves. Of course it still requires the kernel module, so it won't be a total breeze, but it'll be a little more convenient, and perhaps having the added exposure would help more people discover that this extension is actually available too.

**Comment by laurinneff** [comment]
I don't see anything on the link you posted, but I feel like it might be rejected because it writes directly to sysfs. I can ask the GNOME team on Matrix if that's fine or not

**Comment by laurinneff** [comment]
Someone linked [cpupower](/deinstapel/cpupower) as an example of how it could be done, it asks for a password to install a polkit rule on installation, and after that it uses polkit to elevate privileges when writing to sysfs. I could try to implement something similar this evening

**Comment by laurinneff** [comment]
I implemented this now. But I've read the guidelines again and noticed that extensions need to have an OSI-approved license, but this extension currently doesn't have a license. @jibsaramnim, since you already contributed I have to ask for legal reasons, would you be OK with relicensing to the GPL3?

**Comment by jibsaramnim** [comment]
That's 100% ok with me yes! :)

**Comment by laurinneff** [comment]
I submitted the extension now. If anyone wants to follow the review process, [here](https://extensions.gnome.org/review/27863)

**Comment by laurinneff** [comment]
It got rejected, but I fixed the issues and the new review is [here](https://extensions.gnome.org/review/27866)

**Comment by laurinneff** [comment]
This time it got approved, the extension is published [here](https://extensions.gnome.org/extension/4607/asus-zenbook-duo-integration/)

**Comment by jibsaramnim** [comment]
![image](https://user-images.githubusercontent.com/18850/142147733-59254eac-5903-48ca-8d3f-877929428028.png)

This is so nice, it's automatically updating my manually compiled/installed version. What a pleasant experience. Thanks so much for adding this to ego, I hope it'll help a lot more ZenBook Duo folk, especially now that you've added some great new features to boot!
